version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "nuscr.opam" }}
            - deps-

      - run:
          name: Install m4
          command: |
            sudo apt-get update
            sudo apt-get install m4 -y

      - run:
          name: Update opam
          command: opam update

      - run:
          name: Install dependencies
          command: opam install . --deps-only

      - run:
          name: Build
          command: |
            eval $(opam config env)
            dune build

      - run:
          name: Test
          command: |
            eval $(opam config env)
            dune runtest

      - run:
          name: Check format
          command: |
            eval $(opam config env)
            dune build @fmt

      - run:
          name: Build web version
          command: |
            eval $(opam config env)
            WHERE=../docs make -C web deploy

      - persist_to_workspace:
          root: .
          paths:
            - docs

      - save_cache:
          key: deps-{{ checksum "nuscr.opam" }}
          paths:
            - ~/.opam

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "nuscr@no.email"
            git config user.name "NuScr"
      - add_ssh_keys:
          fingerprints:
            - "a3:67:ce:56:d5:34:4c:2a:f4:b8:53:bd:b0:db:2d:cb"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs --dotfiles --message "[skip ci] change" --dist docs


workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
