name: Deploy web

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 4.12.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: nuscr

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-local-packages: nuscr/*.opam

      - name: Cache opam
        uses: actions/cache@v2
        with:
          path: _opam
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('dune-project') }}

      - run: cd nuscr && opam install . --deps-only --with-doc --with-test

      - run: cd nuscr && opam exec -- dune build

      - name: Build docs
        run: |
            cd nuscr
            opam exec -- dune build @doc
            mkdir -p site/docs
            cp -r _build/default/_doc/_html/* site/docs

      - name: Deploy live version
        run: cd nuscr && WHERE=../site opam exec -- make -C web deploy

      - name: Deploy docs
        run: |
            cd nuscr
            git config user.email "nuscr@nuscr.dev"
            git config user.name "NuScr"
            mkdir -p /tmp/deployment
            cp -r site/* /tmp/deployment
            git fetch
            git switch -f gh-pages
            rsync -av --delete --filter='P .git' /tmp/deployment/ .
            git add -A || true
            git commit --amend --reset-author --date=now -m "Deploy docs" || true
            git push --force

