name: Deploy web

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 4.12.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Setup yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: 'web/yarn.lock'

      - name: Cache opam
        uses: actions/cache@v2
        with:
          path: _opam
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('dune-project') }}

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: cd web && yarn

      - name: Build docs
        run: |
            opam exec -- dune build @doc
            mkdir -p site/docs
            cp -r _build/default/_doc/_html/* site/docs

      - name: Deploy live version
        run: WHERE=../site opam exec -- make -C web minify

      - name: Deploy docs
        run: |
            git config user.email "nuscr@nuscr.dev"
            git config user.name "NuScr"
            mkdir -p /tmp/deployment
            cp -r site/* /tmp/deployment
            export DEPLOY_DEST=.
            [[ "$(git branch --show-current)" == "develop" ]] && export DEPLOY_DEST="./dev"
            git fetch
            git switch -f gh-pages
            git clean -fxd
            rsync -av --delete --filter='P .git' /tmp/deployment/ $DEPLOY_DEST
            git add -A || true
            git commit --amend --reset-author --date=now -m "Deploy docs" || true
            git push --force

